### PR TITLE
Added iPhone8 and X

### PR DESCRIPTION
**Pull request by wallin**

### CODE REVIEW

**Comment by nijikon** [comment]
@rikas can this get merged?

**Comment by rikas** [comment]
@nijikon it's done.

Sorry, I was on holidays!

Thanks for this @wallin.

**Comment by rikas** [comment]
Will release new version with this change.

**Comment by nijikon** [comment]
@rikas no worries! Perfect, when you will release we can switch back to this repository from our fork.

**Comment by wallin** [comment]
Thanks @rikas!

**Comment by rikas** [comment]
@nijikon @wallin it's released — `ios-devices 0.2.6`

**Comment by nijikon** [comment]
@rikas that was fast, you rock 🎉

**Pull request merged**
